/**
 * Splits css/dtd-website.css into partials and writes css/dtd-website.css as @imports only.
 * Run: node tools/split_css.js
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const cssDir = path.join(root, 'css');
const cssPath = path.join(cssDir, 'dtd-website.css');

const css = fs.readFileSync(cssPath, 'utf8');
const lines = css.split('\n');

// Line ranges (1-based, inclusive). Boundaries from section comments.
const partials = [
  { name: '_variables.css', start: 1, end: 84 },
  { name: '_base.css', start: 85, end: 364 },
  { name: '_layout.css', start: 365, end: 707 },
  { name: '_components.css', start: 708, end: 2363 },
  { name: '_sections.css', start: 2364, end: lines.length }
];

for (const { name, start, end } of partials) {
  const content = lines.slice(start - 1, end).join('\n');
  fs.writeFileSync(path.join(cssDir, name), content.trimEnd() + '\n', 'utf8');
  console.log('Wrote', name, `(${end - start + 1} lines)`);
}

const mainContent = `/* ========================================
   THE DISCORDING TALES - Website Stylesheet
   Baroque, Maximalist, Interactive Design
   Built from partials - do not edit this file by hand.
   Edit _variables.css, _base.css, _layout.css, _components.css, _sections.css
   ======================================== */

@import "_variables.css";
@import "_base.css";
@import "_layout.css";
@import "_components.css";
@import "_sections.css";
`;

fs.writeFileSync(cssPath, mainContent, 'utf8');
console.log('Wrote dtd-website.css (imports only)');
